# Site settings
email: "humblelistener@icloud.com"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: "UA-74278809-1"

# SEO settings
title: "some writings from a humblelistener"
description:
url: "https://humblelistener.github.io"
twitter_username: "@humblelistener"
default_img:

# Profile settings
name: "P Karthikeyan"
profile_img: https://source.unsplash.com/azbZUNpu1Ag/1600x900
profile: humblelistener is a software engineering professional and a human.
social:
  github: https://github.com/humblelistener
  linkedin: https://linkedin.com/humblelistener
  twitter: https://twitter.com/humblelistener

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
