# Site settings
email:
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: "UA-74278809-1"

# SEO settings
title: "humblelistener"
description:
url: ""
twitter_username: "@humblelistener"
default_img:

# Profile settings
name: "P Karthikeyan"
profile_img:
profile:
social:
  github: "https://github.com/humblelistener"

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
